version: "3.7"

services:
    flask:
        build: ./api-app
        container_name: flask
        restart: always
        ports:
            - "8000:8000"

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "10000:80"
        depends_on:
            - flask